-- 更新activities表，添加缺失的字段
USE dzvote;

-- 添加缺失的列
ALTER TABLE activities
ADD COLUMN IF NOT EXISTS `subtitle` VARCHAR(200) COMMENT '副标题',
ADD COLUMN IF NOT EXISTS `region` VARCHAR(100) COMMENT '区域',
ADD COLUMN IF NOT EXISTS `cover_image` VARCHAR(500) COMMENT '封面图',
ADD COLUMN IF NOT EXISTS `group_count` INT DEFAULT 1 COMMENT '分组数量',
ADD COLUMN IF NOT EXISTS `sms_weight` INT DEFAULT 100 COMMENT '短信权重',
ADD COLUMN IF NOT EXISTS `ivr_weight` INT DEFAULT 100 COMMENT '语音权重',
ADD COLUMN IF NOT EXISTS `web_weight` INT DEFAULT 100 COMMENT '网络权重',
ADD COLUMN IF NOT EXISTS `app_weight` INT DEFAULT 100 COMMENT 'APP权重',
ADD COLUMN IF NOT EXISTS `wechat_weight` INT DEFAULT 100 COMMENT '微信权重',
ADD COLUMN IF NOT EXISTS `pay_weight` INT DEFAULT 100 COMMENT '付费权重',
ADD COLUMN IF NOT EXISTS `ip_limit` INT DEFAULT 0 COMMENT 'IP投票限制',
ADD COLUMN IF NOT EXISTS `enable_captcha` TINYINT DEFAULT 1 COMMENT '是否启用验证码',
ADD COLUMN IF NOT EXISTS `show_votes` TINYINT DEFAULT 1 COMMENT '是否显示票数',
ADD COLUMN IF NOT EXISTS `domain` VARCHAR(200) COMMENT '域名',
ADD COLUMN IF NOT EXISTS `template` VARCHAR(50) COMMENT '模板',
ADD COLUMN IF NOT EXISTS `rules` TEXT COMMENT '规则',
ADD COLUMN IF NOT EXISTS `service_id` VARCHAR(100) COMMENT '活动唯一ID',
ADD COLUMN IF NOT EXISTS `update_by` VARCHAR(50) COMMENT '更新人',
ADD COLUMN IF NOT EXISTS `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除标记';
